export function buildMainPage(freeModels, paidModels) {
    var freeJSON = JSON.stringify(freeModels);
    var paidJSON = JSON.stringify(paidModels);

    var css = [
        ':root{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#c9d1d9;--dim:#8b949e;--blue:#58a6ff;--green:#3fb950;--red:#f85149;--orange:#d29922;--purple:#8957e5}',
        '*{box-sizing:border-box;margin:0;padding:0}',
        'body{font-family:-apple-system,system-ui,sans-serif;background:var(--bg);color:var(--text);min-height:100vh}',
        '.header{background:var(--card);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:1rem}',
        '.header h1{font-size:1.4rem;color:var(--blue)}.header .info{font-size:.8rem;color:var(--dim);background:var(--bg);padding:4px 12px;border-radius:20px;border:1px solid var(--border)}',
        '.nav{display:flex;background:var(--card);border-bottom:1px solid var(--border);overflow-x:auto}',
        '.nav button{background:none;border:none;color:var(--dim);padding:12px 24px;cursor:pointer;font-size:.95rem;border-bottom:2px solid transparent;white-space:nowrap;transition:all .2s}',
        '.nav button:hover{color:var(--text)}.nav button.active{color:var(--blue);border-bottom-color:var(--blue)}',
        '.container{max-width:960px;margin:0 auto;padding:2rem 1rem}',
        '.page{display:none}.page.active{display:block}',
        '.login-box{max-width:360px;margin:4rem auto;text-align:center}',
        '.login-box h2{color:var(--blue);margin-bottom:1rem}.login-box p{color:var(--dim);margin-bottom:1.5rem;font-size:.9rem}',
        'input,textarea{background:var(--bg);color:var(--text);border:1px solid var(--border);padding:12px;border-radius:8px;width:100%;margin-bottom:12px;font-family:monospace;font-size:.9rem}',
        'input:focus,textarea:focus{outline:none;border-color:var(--blue)}',
        '.btn{padding:8px 16px;border-radius:8px;border:none;cursor:pointer;font-size:.85rem;font-weight:600;transition:all .2s;display:inline-block;margin:3px}',
        '.btn:hover{transform:translateY(-1px)}.btn-sm{padding:4px 8px;font-size:.7rem}',
        '.btn-primary{background:var(--green);color:#fff}.btn-blue{background:var(--blue);color:#fff}',
        '.btn-secondary{background:var(--border);color:var(--text)}.btn-danger{background:var(--red);color:#fff}',
        '.btn-builder{background:#ff9900;color:#000;width:100%;padding:14px;font-size:1rem;margin:6px 0}',
        '.card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1.2rem;margin-bottom:12px}',
        '.stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px;margin-bottom:2rem}',
        '.stat-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1rem;text-align:center}',
        '.stat-card .number{font-size:1.8rem;font-weight:700;color:var(--blue)}.stat-card .label{font-size:.75rem;color:var(--dim);margin-top:4px}',
        '.model-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}',
        '.mc{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1rem;position:relative;cursor:pointer;transition:all .2s}',
        '.mc:hover{border-color:var(--blue);transform:translateY(-2px)}.mc h3{font-size:.9rem;margin:.4rem 0}',
        '.mc .ctx{font-size:.7rem;color:var(--dim);margin-top:4px}',
        '.badge{position:absolute;top:8px;right:8px;font-size:.6rem;font-weight:700;padding:2px 8px;border-radius:20px}',
        '.badge.free{background:var(--green);color:#fff}.badge.paid{background:var(--purple);color:#fff}',
        'pre{background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:1rem;overflow-x:auto;font-size:.8rem;max-height:300px;overflow-y:auto;margin-top:12px}',
        '.stitle{color:var(--dim);font-size:.8rem;text-transform:uppercase;letter-spacing:1px;margin:2rem 0 1rem;padding-bottom:.5rem;border-bottom:1px solid var(--border)}',
        '.toast{position:fixed;bottom:20px;right:20px;padding:12px 24px;border-radius:8px;color:#fff;font-weight:600;z-index:9999;display:none}',
        '.aresult{margin-top:1.5rem;padding:1rem;background:var(--card);border:1px solid var(--border);border-radius:8px;display:none}',
        '.aresult a{color:var(--blue);word-break:break-all}',
        '.row{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}.hidden{display:none}',
        // Provider grid styles
        '.prov-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}',
        '.prov-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1rem;position:relative;transition:border-color .2s}',
        '.prov-card.healthy{border-color:var(--green)}.prov-card.unhealthy{border-color:var(--red)}.prov-card.disabled{border-color:var(--dim);opacity:.6}',
        '.prov-card.cooldown{border-color:var(--orange)}.prov-card.refreshing{border-color:var(--orange)}',
        '.prov-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}',
        '.prov-name{font-weight:700;font-size:.85rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:140px}',
        '.prov-status{width:10px;height:10px;border-radius:50%;flex-shrink:0}',
        '.prov-status.healthy{background:var(--green)}.prov-status.unhealthy{background:var(--red)}.prov-status.disabled{background:var(--dim)}',
        '.prov-status.cooldown{background:var(--orange)}.prov-status.refreshing{background:var(--orange)}',
        '.prov-bar{height:8px;background:var(--border);border-radius:4px;overflow:hidden;margin:6px 0}',
        '.prov-bar-fill{height:100%;border-radius:4px;transition:width .5s ease}',
        '.prov-pct{font-size:1.1rem;font-weight:700;text-align:center;margin:4px 0}',
        '.prov-detail{font-size:.7rem;color:var(--dim);text-align:center}',
        '.prov-actions{display:flex;gap:3px;margin-top:8px;justify-content:center;flex-wrap:wrap}',
        '.prov-error{font-size:.65rem;color:var(--red);margin-top:4px;word-break:break-all}',
        '.prov-summary{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem;padding:.8rem 1rem;background:var(--card);border:1px solid var(--border);border-radius:10px}',
        '.prov-summary-item{text-align:center}.prov-summary-item .val{font-size:1.4rem;font-weight:700;color:var(--blue)}',
        '.prov-summary-item .lbl{font-size:.7rem;color:var(--dim)}',
    ].join('\n');

    var body = [
        '<div class="header"><h1>&#x1F680; Kiro2 API</h1><span class="info" id="hInfo">Not logged in</span></div>',
        '<div class="nav" id="navBar">',
        '<button onclick="sp(\'models\')" id="nav-models" class="active">Models</button>',
        '<button onclick="sp(\'login\')" id="nav-login">Login</button>',
        '</div>',
        '<div class="container">',
        // Login
        '<div class="page active" id="page-login"><div class="login-box">',
        '<h2>Admin Login</h2><p>Enter admin password to manage accounts</p>',
        '<input type="password" id="pwdInput" placeholder="Admin password">',
        '<button class="btn btn-primary" onclick="doLogin()" style="width:100%;padding:14px;font-size:1rem">Login</button>',
        '</div></div>',
        // Models
        '<div class="page" id="page-models">',
        '<div class="stitle">Free Tier</div><div class="model-grid" id="freeM"></div>',
        '<div class="stitle">Pro Tier</div><div class="model-grid" id="paidM"></div>',
        '</div>',
        // Providers (always visible after login)
        '<div class="page" id="page-providers">',
        '<div class="stitle">Kiro Providers</div>',
        '<div class="prov-summary" id="provSummary"></div>',
        '<div class="prov-grid" id="provGrid"></div>',
        '<div class="row" style="margin-top:1rem">',
        '<button class="btn btn-blue" onclick="checkAllCreds()">Recheck All</button>',
        '<button class="btn btn-primary" onclick="refreshAll()">Refresh Tokens</button>',
        '<button class="btn btn-secondary" onclick="rescan()">Rescan Configs</button>',
        '</div>',
        '</div>',
        // Dashboard
        '<div class="page" id="page-dashboard">',
        '<div class="stitle">Stats</div><div class="stats-grid" id="sGrid"></div>',
        '</div>',
        // Add Account
        '<div class="page" id="page-auth">',
        '<div class="stitle">AWS Builder ID</div>',
        '<div style="max-width:400px">',
        '<button class="btn btn-builder" onclick="oAuth(\'builder-id\')">&#x1F7E0; Sign in with AWS Builder ID</button>',
        '</div>',
        '<div class="aresult" id="aRes"></div>',
        '<div class="stitle" style="margin-top:2rem">Import JSON Credentials</div>',
        '<textarea id="impJSON" rows="5" placeholder=\'{"accessToken":"...","refreshToken":"..."}\'></textarea>',
        '<button class="btn btn-primary" onclick="impCreds()">Import</button>',
        '<div class="stitle" style="margin-top:2rem">Batch Refresh Tokens</div>',
        '<textarea id="bTokens" rows="4" placeholder="One token per line"></textarea>',
        '<button class="btn btn-primary" onclick="batchImp()">Batch Import</button>',
        '<pre id="bRes" class="hidden"></pre>',
        '</div>',
        // Export
        '<div class="page" id="page-export">',
        '<div class="stitle">Export Credentials</div>',
        '<p style="color:var(--dim);margin-bottom:1rem;font-size:.85rem">Backup for redeployment.</p>',
        '<div class="row"><button class="btn btn-blue" onclick="expJSON()">JSON</button><button class="btn btn-primary" onclick="expB64()">Base64 (copy)</button></div>',
        '<pre id="expBox" class="hidden"></pre>',
        '</div>',
        // Settings
        '<div class="page" id="page-settings">',
        '<div class="stitle">API Key</div>',
        '<p style="color:var(--dim);margin-bottom:1rem;font-size:.85rem">Change the API key for /v1/chat/completions</p>',
        '<div id="curKeyBox" style="margin-bottom:8px"></div>',
        '<input type="text" id="newKeyInput" placeholder="New API key (min 4 chars)">',
        '<button class="btn btn-primary" onclick="changeKey()">Change API Key</button>',
        '</div>',
        '</div>',
        '<div class="toast" id="toast"></div>',
    ].join('\n');

    var js = [
        'var FM=' + freeJSON + ',PM=' + paidJSON + ';',
        'var pwd=localStorage.getItem("k2pwd")||"";',
        'var loggedIn=false;',
        'var provRefreshTimer=null;',
        '',
        'function sp(n){',
        '  if(["providers","dashboard","auth","export","settings"].indexOf(n)!==-1&&!loggedIn){sp("login");toast("Login first","#f85149");return;}',
        '  var ps=document.querySelectorAll(".page"),bs=document.querySelectorAll(".nav button");',
        '  for(var i=0;i<ps.length;i++)ps[i].classList.remove("active");',
        '  for(var i=0;i<bs.length;i++)bs[i].classList.remove("active");',
        '  var p=document.getElementById("page-"+n),b=document.getElementById("nav-"+n);',
        '  if(p)p.classList.add("active");if(b)b.classList.add("active");',
        '  if(n==="providers")loadProviders();',
        '  if(n==="dashboard")loadDash();',
        '  if(n==="models")renderM();',
        '  if(n==="settings")loadKey();',
        '}',
        '',
        'function doLogin(){',
        '  pwd=document.getElementById("pwdInput").value;',
        '  if(!pwd){toast("Enter password","#f85149");return;}',
        '  fetch("/admin/stats",{headers:{"Authorization":"Bearer "+pwd}})',
        '  .then(function(r){if(!r.ok)throw new Error();return r.json();})',
        '  .then(function(){',
        '    loggedIn=true;localStorage.setItem("k2pwd",pwd);',
        '    document.getElementById("hInfo").textContent="Admin OK";',
        '    document.getElementById("hInfo").style.borderColor="#3fb950";',
        '    buildNav();toast("Logged in!","#3fb950");sp("providers");',
        '    startProvAutoRefresh();',
        '  }).catch(function(){toast("Wrong password","#f85149");pwd="";localStorage.removeItem("k2pwd");});',
        '}',
        '',
        'function buildNav(){',
        '  var nav=document.getElementById("navBar");nav.innerHTML="";',
        '  var tabs=[["models","Models"],["providers","Providers"],["dashboard","Stats"],["auth","Add Account"],["export","Export"],["settings","Settings"]];',
        '  for(var i=0;i<tabs.length;i++){var btn=document.createElement("button");btn.id="nav-"+tabs[i][0];btn.textContent=tabs[i][1];btn.setAttribute("data-p",tabs[i][0]);btn.onclick=function(){sp(this.getAttribute("data-p"));};nav.appendChild(btn);}',
        '}',
        '',
        'document.getElementById("pwdInput").addEventListener("keydown",function(e){if(e.key==="Enter")doLogin();});',
        'function hdr(){return{"Authorization":"Bearer "+pwd,"Content-Type":"application/json"};}',
        '',
        '// Models',
        'function renderM(){rg("freeM",FM,"free","FREE");rg("paidM",PM,"paid","PRO");}',
        'function rg(id,models,bc,bt){',
        '  var c=document.getElementById(id);c.innerHTML="";',
        '  for(var i=0;i<models.length;i++){var m=models[i];var d=document.createElement("div");d.className="mc";d.setAttribute("data-m",m.id);d.onclick=function(){cp(this.getAttribute("data-m"));};d.innerHTML="<span class=\\"badge "+bc+"\\">"+bt+"</span><h3>"+m.name+"</h3><div class=\\"ctx\\">"+m.id+" | "+(m.context||"?")+"</div><small style=\\"color:var(--dim)\\">Click to copy</small>";c.appendChild(d);}',
        '}',
        '',
        '// Provider grid',
        'function loadProviders(){',
        '  fetch("/admin/stats",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){',
        '    var accts=d.accounts||[];',
        '    // Summary',
        '    var total=accts.length;var hCount=0;var uCount=0;var totalUsed=0;var totalLimit=0;',
        '    for(var i=0;i<accts.length;i++){',
        '      if(accts[i].status==="healthy")hCount++;',
        '      if(accts[i].status==="unhealthy"||accts[i].status==="disabled")uCount++;',
        '      if(accts[i].lastUsage){totalUsed+=accts[i].lastUsage.usedCount;totalLimit+=accts[i].lastUsage.limitCount;}',
        '    }',
        '    document.getElementById("provSummary").innerHTML=',
        '      "<div class=\\"prov-summary-item\\"><div class=\\"val\\">"+total+"</div><div class=\\"lbl\\">Total</div></div>"+',
        '      "<div class=\\"prov-summary-item\\"><div class=\\"val\\" style=\\"color:var(--green)\\">"+hCount+"</div><div class=\\"lbl\\">Healthy</div></div>"+',
        '      "<div class=\\"prov-summary-item\\"><div class=\\"val\\" style=\\"color:var(--red)\\">"+uCount+"</div><div class=\\"lbl\\">Down</div></div>"+',
        '      "<div class=\\"prov-summary-item\\"><div class=\\"val\\">"+totalUsed+"/"+totalLimit+"</div><div class=\\"lbl\\">Credits Used</div></div>";',
        '    // Grid',
        '    var grid=document.getElementById("provGrid");',
        '    if(accts.length===0){grid.innerHTML="<div class=\\"card\\"><p style=\\"color:var(--dim)\\">No providers. Go to Add Account.</p></div>";return;}',
        '    var html="";',
        '    for(var i=0;i<accts.length;i++){',
        '      var a=accts[i];',
        '      var used=a.lastUsage?a.lastUsage.usedCount:0;',
        '      var limit=a.lastUsage?a.lastUsage.limitCount:0;',
        '      var hasErr=a.lastUsage&&a.lastUsage.error;',
        '      var pct=limit>0?Math.round(used/limit*100):0;',
        '      var barColor=pct<60?"var(--green)":pct<85?"var(--orange)":"var(--red)";',
        '      if(a.status==="disabled")barColor="var(--dim)";',
        '      var isDis=a.status==="disabled";',
        '      html+="<div class=\\"prov-card "+a.status+"\\">";',
        '      html+="<div class=\\"prov-header\\"><span class=\\"prov-name\\" title=\\""+a.id+"\\">"+a.label.replace(/\\.json$/,"")+"</span><span class=\\"prov-status "+a.status+"\\"></span></div>";',
        '      html+="<div class=\\"prov-pct\\" style=\\"color:"+barColor+"\\">"+pct+"%</div>";',
        '      html+="<div class=\\"prov-bar\\"><div class=\\"prov-bar-fill\\" style=\\"width:"+pct+"%;background:"+barColor+"\\"></div></div>";',
        '      html+="<div class=\\"prov-detail\\">"+used+".00 / "+limit+".00</div>";',
        '      if(hasErr)html+="<div class=\\"prov-error\\">"+a.lastUsage.error+"</div>";',
        '      if(a.lastError&&!hasErr)html+="<div class=\\"prov-error\\">"+a.lastError+"</div>";',
        '      html+="<div class=\\"prov-actions\\">";',
        '      html+="<button class=\\"btn btn-sm btn-blue\\" onclick=\\"hc(\'"+a.id+"\')\\"  >Check</button>";',
        '      if(isDis)html+="<button class=\\"btn btn-sm btn-primary\\" onclick=\\"enAcc(\'"+a.id+"\')\\"  >Enable</button>";',
        '      else html+="<button class=\\"btn btn-sm btn-secondary\\" onclick=\\"disAcc(\'"+a.id+"\')\\"  >Disable</button>";',
        '      html+="<button class=\\"btn btn-sm btn-danger\\" onclick=\\"rmAcc(\'"+a.id+"\')\\"  >Remove</button>";',
        '      html+="</div></div>";',
        '    }',
        '    grid.innerHTML=html;',
        '  }).catch(function(){toast("Load failed","#f85149");});',
        '}',
        '',
        'function startProvAutoRefresh(){',
        '  if(provRefreshTimer)return;',
        '  provRefreshTimer=setInterval(function(){',
        '    var provPage=document.getElementById("page-providers");',
        '    if(provPage&&provPage.classList.contains("active"))loadProviders();',
        '  },30000);',
        '}',
        '',
        '// Stats',
        'function loadDash(){',
        '  fetch("/admin/stats",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){',
        '    var s=d.stats;',
        '    document.getElementById("sGrid").innerHTML=sc(s.totalRequestsAllTime,"Requests")+sc(s.totalErrorsAllTime,"Errors")+sc(s.uniqueUsersAllTime,"Users")+sc(s.currentOnlineUsers,"Online")+sc(Math.floor(s.uptimeSeconds/60)+"m","Uptime");',
        '  }).catch(function(){toast("Load failed","#f85149");});',
        '}',
        'function sc(v,l){return "<div class=\\"stat-card\\"><div class=\\"number\\">"+v+"</div><div class=\\"label\\">"+l+"</div></div>";}',
        '',
        '// Account actions',
        'function hc(id){toast("Checking...","#58a6ff");fetch("/admin/account/"+id+"/health-check",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(d){if(d.healthy)toast(id+": "+d.usedCount+"/"+d.limitCount,"#3fb950");else toast(id+": "+d.error,"#f85149");loadProviders();});}',
        'function checkAllCreds(){toast("Checking all...","#58a6ff");fetch("/admin/check-all-credits",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(){toast("Done","#3fb950");loadProviders();}).catch(function(e){toast(e.message,"#f85149");});}',
        'function disAcc(id){fetch("/admin/account/"+id+"/disable",{method:"POST",headers:hdr()}).then(function(){toast("Disabled","#d29922");loadProviders();});}',
        'function enAcc(id){fetch("/admin/account/"+id+"/enable",{method:"POST",headers:hdr()}).then(function(){toast("Enabled","#3fb950");loadProviders();});}',
        'function rmAcc(id){if(!confirm("Remove "+id+"?"))return;fetch("/admin/account/"+id+"/remove",{method:"POST",headers:hdr()}).then(function(){toast("Removed","#f85149");loadProviders();});}',
        'function refreshAll(){fetch("/admin/refresh-all",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(d){toast("Refreshed "+d.refreshed+"/"+d.total,"#3fb950");loadProviders();});}',
        'function rescan(){fetch("/admin/rescan",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(d){toast("Found "+d.added+" new","#3fb950");loadProviders();});}',
        '',
        '// OAuth',
        'function oAuth(m){',
        '  var el=document.getElementById("aRes");el.style.display="block";',
        '  el.innerHTML="<p style=\\"color:var(--dim)\\">Starting...</p>";',
        '  fetch("/auth/kiro/oauth",{method:"POST",headers:hdr(),body:JSON.stringify({method:m})})',
        '  .then(function(r){return r.json()})',
        '  .then(function(d){',
        '    if(d.authUrl){el.innerHTML="<p>Open this link:</p><a href=\\""+d.authUrl+"\\" target=\\"_blank\\">"+d.authUrl+"</a><p style=\\"margin-top:1rem;color:var(--dim)\\">Account auto-adds after auth.</p>";window.open(d.authUrl,"_blank");}',
        '    else el.innerHTML="<p style=\\"color:var(--red)\\">Error: "+(d.error||"Unknown")+"</p>";',
        '  }).catch(function(e){el.innerHTML="<p style=\\"color:var(--red)\\">"+e.message+"</p>";});',
        '}',
        '',
        '// Import / Batch',
        'function impCreds(){var raw=document.getElementById("impJSON").value;var data;try{data=JSON.parse(raw);}catch(e){toast("Invalid JSON","#f85149");return;}',
        '  fetch("/admin/credentials/import",{method:"POST",headers:hdr(),body:JSON.stringify(data)}).then(function(r){return r.json()}).then(function(d){if(d.success){toast("Imported!","#3fb950");document.getElementById("impJSON").value="";loadProviders();}else toast("Failed: "+d.error,"#f85149");});}',
        'function batchImp(){var lines=document.getElementById("bTokens").value.split("\\n").filter(function(s){return s.trim();});if(!lines.length){toast("No tokens","#f85149");return;}',
        '  fetch("/admin/credentials/batch-import",{method:"POST",headers:hdr(),body:JSON.stringify({refreshTokens:lines})}).then(function(r){return r.json()}).then(function(d){var el=document.getElementById("bRes");el.classList.remove("hidden");el.textContent=JSON.stringify(d,null,2);toast(d.success+" ok","#3fb950");loadProviders();});}',
        '',
        '// Export',
        'function expJSON(){fetch("/admin/credentials/export",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){var el=document.getElementById("expBox");el.classList.remove("hidden");el.textContent=JSON.stringify(d.credentials,null,2);});}',
        'function expB64(){fetch("/admin/credentials/export-base64",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){var el=document.getElementById("expBox");el.classList.remove("hidden");el.textContent=d.base64;cp(d.base64);toast("Base64 copied!","#3fb950");});}',
        '',
        '// Settings',
        'function loadKey(){fetch("/admin/settings/api-key",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){var k=d.apiKey||"";document.getElementById("curKeyBox").innerHTML="<strong>Current:</strong> <code>"+k.substring(0,4)+"..."+k.substring(k.length-4)+"</code>";});}',
        'function changeKey(){var k=document.getElementById("newKeyInput").value;if(!k||k.length<4){toast("Min 4 chars","#f85149");return;}',
        '  fetch("/admin/settings/api-key",{method:"POST",headers:hdr(),body:JSON.stringify({apiKey:k})}).then(function(r){return r.json()}).then(function(d){if(d.success){toast("Key changed!","#3fb950");document.getElementById("newKeyInput").value="";loadKey();}else toast(d.error||"Failed","#f85149");});}',
        '',
        '// Utils',
        'function cp(text){navigator.clipboard.writeText(text).then(function(){toast("Copied!","#3fb950")}).catch(function(){var ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta);toast("Copied!","#3fb950");});}',
        'function toast(m,c){var t=document.getElementById("toast");t.textContent=m;t.style.background=c||"#3fb950";t.style.display="block";setTimeout(function(){t.style.display="none";},3000);}',
        '',
        '// Auto-login',
        'function tryAutoLogin(){if(!pwd)return;',
        '  fetch("/admin/stats",{headers:{"Authorization":"Bearer "+pwd}}).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(function(){',
        '    loggedIn=true;document.getElementById("hInfo").textContent="Admin OK";document.getElementById("hInfo").style.borderColor="#3fb950";',
        '    buildNav();sp("providers");startProvAutoRefresh();',
        '  }).catch(function(){pwd="";localStorage.removeItem("k2pwd");});}',
        '',
        'renderM();',
        'if(pwd)tryAutoLogin();else sp("models");',
    ].join('\n');

    return '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>Kiro2 API</title>\n<style>\n' + css + '\n</style>\n</head>\n<body>\n' + body + '\n<script>\n' + js + '\n</script>\n</body>\n</html>';
}

export function buildModelsPage(freeModels, paidModels) {
    var fCards = '';
    for (var i = 0; i < freeModels.length; i++) {
        var m = freeModels[i];
        fCards += '<div class="mc" data-m="' + m.id + '"><span class="b free">FREE</span><h3>' + m.name + '</h3><div class="ctx">' + m.id + ' | ' + (m.context || '?') + '</div><small>Click to copy</small></div>';
    }
    var pCards = '';
    for (var i = 0; i < paidModels.length; i++) {
        var m = paidModels[i];
        pCards += '<div class="mc" data-m="' + m.id + '"><span class="b paid">PRO</span><h3>' + m.name + '</h3><div class="ctx">' + m.id + ' | ' + (m.context || '?') + '</div><small>Click to copy</small></div>';
    }
    return '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kiro2 Models</title>'
        + '<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:system-ui;background:#0d1117;color:#c9d1d9;padding:2rem}'
        + 'h1{text-align:center;margin-bottom:.5rem;color:#58a6ff}h2{margin:2rem 0 1rem;color:#8b949e;border-bottom:1px solid #21262d;padding-bottom:.5rem}'
        + '.sub{text-align:center;color:#8b949e;margin-bottom:2rem}'
        + '.g{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:10px}'
        + '.mc{background:#161b22;border:1px solid #30363d;border-radius:10px;padding:1rem;position:relative;cursor:pointer;transition:all .2s}'
        + '.mc:hover{transform:translateY(-2px);border-color:#58a6ff}.mc h3{margin:.4rem 0;font-size:.9rem}'
        + '.mc .ctx{font-size:.7rem;color:#8b949e;margin-top:4px}.mc small{color:#8b949e}'
        + '.b{position:absolute;top:8px;right:8px;font-size:.6rem;font-weight:700;padding:2px 8px;border-radius:20px}'
        + '.b.free{background:#238636;color:#fff}.b.paid{background:#8957e5;color:#fff}'
        + '.t{position:fixed;bottom:20px;right:20px;background:#238636;color:#fff;padding:10px 20px;border-radius:8px;display:none;z-index:999}</style></head><body>'
        + '<h1>Kiro2 API</h1><p class="sub">Available Models</p>'
        + '<h2>Free Tier</h2><div class="g">' + fCards + '</div>'
        + '<h2>Pro Tier</h2><div class="g">' + pCards + '</div>'
        + '<div class="t" id="t">Copied!</div>'
        + '<script>document.querySelectorAll(".mc").forEach(function(el){el.onclick=function(){var m=this.getAttribute("data-m");navigator.clipboard.writeText(m).then(function(){var t=document.getElementById("t");t.style.display="block";setTimeout(function(){t.style.display="none"},1500)});};})</script></body></html>';
}
