/**
 * All HTML pages as exported functions.
 * Separated from server.js to avoid template literal hell.
 */

export function buildMainPage(freeModels, paidModels) {
    const freeJSON = JSON.stringify(freeModels);
    const paidJSON = JSON.stringify(paidModels);

    // Build the HTML in chunks to avoid truncation
    var css = [
        ':root{--bg:#0d1117;--card:#161b22;--border:#30363d;--text:#c9d1d9;--dim:#8b949e;--blue:#58a6ff;--green:#3fb950;--red:#f85149;--orange:#d29922;--purple:#8957e5}',
        '*{box-sizing:border-box;margin:0;padding:0}',
        'body{font-family:-apple-system,system-ui,sans-serif;background:var(--bg);color:var(--text);min-height:100vh}',
        '.header{background:var(--card);border-bottom:1px solid var(--border);padding:1rem 2rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:1rem}',
        '.header h1{font-size:1.4rem;color:var(--blue)}',
        '.header .api-info{font-size:.8rem;color:var(--dim);background:var(--bg);padding:4px 12px;border-radius:20px;border:1px solid var(--border)}',
        '.nav{display:flex;gap:0;background:var(--card);border-bottom:1px solid var(--border);overflow-x:auto}',
        '.nav button{background:none;border:none;color:var(--dim);padding:12px 24px;cursor:pointer;font-size:.95rem;border-bottom:2px solid transparent;white-space:nowrap;transition:all .2s}',
        '.nav button:hover{color:var(--text);background:rgba(255,255,255,.03)}',
        '.nav button.active{color:var(--blue);border-bottom-color:var(--blue)}',
        '.container{max-width:900px;margin:0 auto;padding:2rem 1rem}',
        '.page{display:none}.page.active{display:block}',
        '.login-box{max-width:360px;margin:4rem auto;text-align:center}',
        '.login-box h2{color:var(--blue);margin-bottom:1rem;font-size:1.6rem}',
        '.login-box p{color:var(--dim);margin-bottom:1.5rem;font-size:.9rem}',
        'input,textarea{background:var(--bg);color:var(--text);border:1px solid var(--border);padding:12px;border-radius:8px;width:100%;margin-bottom:12px;font-family:monospace;font-size:.9rem}',
        'input:focus,textarea:focus{outline:none;border-color:var(--blue)}',
        '.btn{padding:10px 20px;border-radius:8px;border:none;cursor:pointer;font-size:.9rem;font-weight:600;transition:all .2s;display:inline-block;margin:4px}',
        '.btn:hover{transform:translateY(-1px)}',
        '.btn-primary{background:var(--green);color:#fff}.btn-primary:hover{background:#2ea043}',
        '.btn-blue{background:var(--blue);color:#fff}.btn-blue:hover{background:#4093e0}',
        '.btn-secondary{background:var(--border);color:var(--text)}.btn-secondary:hover{background:#3d444d}',
        '.btn-google{background:#4285f4;color:#fff;width:100%;padding:14px;font-size:1rem;margin:6px 0}',
        '.btn-github{background:#333;color:#fff;width:100%;padding:14px;font-size:1rem;margin:6px 0}',
        '.btn-builder{background:#ff9900;color:#000;width:100%;padding:14px;font-size:1rem;margin:6px 0}',
        '.card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1.2rem;margin-bottom:12px}',
        '.card:hover{border-color:var(--blue)}',
        '.stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px;margin-bottom:2rem}',
        '.stat-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1rem;text-align:center}',
        '.stat-card .number{font-size:2rem;font-weight:700;color:var(--blue)}',
        '.stat-card .label{font-size:.8rem;color:var(--dim);margin-top:4px}',
        '.as{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}',
        '.as.healthy{background:var(--green)}.as.unhealthy{background:var(--red)}.as.refreshing{background:var(--orange)}.as.cooldown{background:var(--orange)}',
        '.model-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:12px}',
        '.model-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:1.2rem;position:relative;cursor:pointer;transition:all .2s}',
        '.model-card:hover{border-color:var(--blue);transform:translateY(-2px)}',
        '.model-card h3{font-size:.95rem;margin:.4rem 0;word-break:break-all}',
        '.badge{position:absolute;top:10px;right:10px;font-size:.65rem;font-weight:700;padding:3px 8px;border-radius:20px}',
        '.badge.free{background:var(--green);color:#fff}.badge.paid{background:var(--purple);color:#fff}',
        'pre{background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:1rem;overflow-x:auto;font-size:.8rem;max-height:300px;overflow-y:auto;margin-top:12px}',
        '.section-title{color:var(--dim);font-size:.85rem;text-transform:uppercase;letter-spacing:1px;margin:2rem 0 1rem;padding-bottom:.5rem;border-bottom:1px solid var(--border)}',
        '.toast{position:fixed;bottom:20px;right:20px;padding:12px 24px;border-radius:8px;color:#fff;font-weight:600;z-index:9999;display:none;animation:slideUp .3s ease}',
        '@keyframes slideUp{from{transform:translateY(20px);opacity:0}to{transform:translateY(0);opacity:1}}',
        '.auth-result{margin-top:1.5rem;padding:1rem;background:var(--card);border:1px solid var(--border);border-radius:8px;display:none}',
        '.auth-result a{color:var(--blue);word-break:break-all}',
        '.row{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}',
        '.hidden{display:none}',
    ].join('\n');

    var bodyHTML = [
        '<div class="header">',
        '  <h1>&#x1F680; Kiro2 API</h1>',
        '  <span class="api-info" id="headerInfo">Not logged in</span>',
        '</div>',
        '<div class="nav" id="navBar">',
        '  <button onclick="showPage(\'models\')" id="nav-models" class="active">&#x1F4CB; Models</button>',
        '  <button onclick="showPage(\'login\')" id="nav-login">&#x1F512; Login</button>',
        '</div>',
        '<div class="container">',
        '',
        '<!-- LOGIN -->',
        '<div class="page active" id="page-login">',
        '  <div class="login-box">',
        '    <h2>&#x1F510; Admin Login</h2>',
        '    <p>Enter admin password to manage accounts</p>',
        '    <input type="password" id="pwdInput" placeholder="Admin password">',
        '    <button class="btn btn-primary" onclick="doLogin()" style="width:100%;padding:14px;font-size:1rem">Login</button>',
        '  </div>',
        '</div>',
        '',
        '<!-- MODELS -->',
        '<div class="page" id="page-models">',
        '  <div class="section-title">&#x1F31F; Free Tier Models</div>',
        '  <div class="model-grid" id="freeModels"></div>',
        '  <div class="section-title">&#x1F48E; Pro Tier Models</div>',
        '  <div class="model-grid" id="paidModels"></div>',
        '</div>',
        '',
        '<!-- DASHBOARD -->',
        '<div class="page" id="page-dashboard">',
        '  <div class="section-title">&#x1F4CA; Live Stats</div>',
        '  <div class="stats-grid" id="statsGrid"></div>',
        '  <div class="section-title">&#x1F464; Accounts</div>',
        '  <div id="accountsList"></div>',
        '  <div class="row" style="margin-top:1rem">',
        '    <button class="btn btn-blue" onclick="refreshAll()">&#x1F504; Refresh All</button>',
        '    <button class="btn btn-secondary" onclick="rescanConfigs()">&#x1F50D; Rescan Configs</button>',
        '  </div>',
        '</div>',
        '',
        '<!-- ADD ACCOUNT -->',
        '<div class="page" id="page-auth">',
        '  <div class="section-title">&#x1F511; Add Account via OAuth</div>',
        '  <div style="max-width:400px">',
        '    <button class="btn btn-google" onclick="startOAuth(\'google\')">&#x1F535; Google</button>',
        '    <button class="btn btn-github" onclick="startOAuth(\'github\')">&#x26AB; GitHub</button>',
        '    <button class="btn btn-builder" onclick="startOAuth(\'builder-id\')">&#x1F7E0; AWS Builder ID</button>',
        '  </div>',
        '  <div class="auth-result" id="authResult"></div>',
        '  <div class="section-title" style="margin-top:3rem">&#x1F4E4; Import JSON</div>',
        '  <textarea id="importJSON" rows="5" placeholder=\'{"accessToken":"...","refreshToken":"..."}\'></textarea>',
        '  <button class="btn btn-primary" onclick="importCreds()">Import</button>',
        '  <div class="section-title" style="margin-top:2rem">&#x1F4E4; Batch Refresh Tokens</div>',
        '  <textarea id="batchTokens" rows="5" placeholder="One token per line"></textarea>',
        '  <button class="btn btn-primary" onclick="batchImport()">Batch Import</button>',
        '  <pre id="batchResult" class="hidden"></pre>',
        '</div>',
        '',
        '<!-- EXPORT -->',
        '<div class="page" id="page-export">',
        '  <div class="section-title">&#x1F4E6; Export Credentials</div>',
        '  <p style="color:var(--dim);margin-bottom:1rem;font-size:.9rem">Export for backup or redeployment.</p>',
        '  <div class="row">',
        '    <button class="btn btn-blue" onclick="exportJSON()">&#x1F4E5; JSON</button>',
        '    <button class="btn btn-primary" onclick="exportBase64()">&#x1F4CB; Base64</button>',
        '  </div>',
        '  <pre id="exportBox" class="hidden"></pre>',
        '</div>',
        '',
        '</div>',
        '<div class="toast" id="toast"></div>',
    ].join('\n');

    var js = [
        'var FREE_MODELS = ' + freeJSON + ';',
        'var PAID_MODELS = ' + paidJSON + ';',
        'var adminPwd = "";',
        'var loggedIn = false;',
        '',
        'function showPage(name) {',
        '  if (["dashboard","auth","export"].indexOf(name) !== -1 && !loggedIn) {',
        '    showPage("login"); toast("Login first","#f85149"); return;',
        '  }',
        '  var pages = document.querySelectorAll(".page");',
        '  for (var i = 0; i < pages.length; i++) pages[i].classList.remove("active");',
        '  var btns = document.querySelectorAll(".nav button");',
        '  for (var i = 0; i < btns.length; i++) btns[i].classList.remove("active");',
        '  var p = document.getElementById("page-" + name);',
        '  var b = document.getElementById("nav-" + name);',
        '  if (p) p.classList.add("active");',
        '  if (b) b.classList.add("active");',
        '  if (name === "dashboard") loadDashboard();',
        '  if (name === "models") renderModels();',
        '}',
        '',
        'function doLogin() {',
        '  adminPwd = document.getElementById("pwdInput").value;',
        '  if (!adminPwd) { toast("Enter password","#f85149"); return; }',
        '  fetch("/admin/stats", { headers: { "Authorization": "Bearer " + adminPwd } })',
        '    .then(function(r) { if (!r.ok) throw new Error("bad"); return r.json(); })',
        '    .then(function() {',
        '      loggedIn = true;',
        '      document.getElementById("headerInfo").textContent = "Admin \\u2714";',
        '      document.getElementById("headerInfo").style.borderColor = "#3fb950";',
        '      var nav = document.getElementById("navBar");',
        '      nav.innerHTML = "";',
        '      var tabs = [["models","Models"],["dashboard","Dashboard"],["auth","Add Account"],["export","Export"]];',
        '      for (var i = 0; i < tabs.length; i++) {',
        '        var btn = document.createElement("button");',
        '        btn.id = "nav-" + tabs[i][0];',
        '        btn.textContent = tabs[i][1];',
        '        btn.setAttribute("data-page", tabs[i][0]);',
        '        btn.onclick = function() { showPage(this.getAttribute("data-page")); };',
        '        nav.appendChild(btn);',
        '      }',
        '      toast("Logged in!","#3fb950");',
        '      showPage("dashboard");',
        '    })',
        '    .catch(function() { toast("Wrong password","#f85149"); adminPwd = ""; });',
        '}',
        '',
        'document.getElementById("pwdInput").addEventListener("keydown", function(e) {',
        '  if (e.key === "Enter") doLogin();',
        '});',
        '',
        'function hdr() { return { "Authorization": "Bearer " + adminPwd, "Content-Type": "application/json" }; }',
        '',
        'function renderModels() {',
        '  renderGrid("freeModels", FREE_MODELS, "free", "FREE");',
        '  renderGrid("paidModels", PAID_MODELS, "paid", "PRO");',
        '}',
        'function renderGrid(id, models, bc, bt) {',
        '  var c = document.getElementById(id); c.innerHTML = "";',
        '  for (var i = 0; i < models.length; i++) {',
        '    var d = document.createElement("div"); d.className = "model-card";',
        '    d.setAttribute("data-model", models[i]);',
        '    d.onclick = function() { copyText(this.getAttribute("data-model")); };',
        '    d.innerHTML = "<span class=\\"badge " + bc + "\\">" + bt + "</span><h3>" + models[i] + "</h3><small style=\\"color:var(--dim)\\">Click to copy</small>";',
        '    c.appendChild(d);',
        '  }',
        '}',
        '',
        'function loadDashboard() {',
        '  fetch("/admin/stats", { headers: hdr() })',
        '    .then(function(r) { return r.json(); })',
        '    .then(function(d) {',
        '      var s = d.stats;',
        '      document.getElementById("statsGrid").innerHTML =',
        '        sc(s.totalRequestsAllTime,"Requests") +',
        '        sc(s.totalErrorsAllTime,"Errors") +',
        '        sc(s.uniqueUsersAllTime,"Total Users") +',
        '        sc(s.currentOnlineUsers,"Online Now") +',
        '        sc(Math.floor(s.uptimeSeconds/60)+"m","Uptime");',
        '      var list = document.getElementById("accountsList");',
        '      if (!d.accounts || d.accounts.length === 0) {',
        '        list.innerHTML = "<div class=\\"card\\"><p style=\\"color:var(--dim)\\">No accounts. Go to Add Account.</p></div>";',
        '        return;',
        '      }',
        '      var html = "";',
        '      for (var i = 0; i < d.accounts.length; i++) {',
        '        var a = d.accounts[i];',
        '        html += "<div class=\\"card\\"><span class=\\"as " + a.status + "\\"></span><strong>" + a.id + "</strong> <span style=\\"color:var(--dim)\\">(" + a.label + ")</span><div style=\\"margin-top:8px;font-size:.85rem;color:var(--dim)\\">Auth: " + a.authMethod + " | Region: " + a.region + " | Active: " + a.activeRequests + " | Total: " + a.totalRequests + " | Errors: " + a.totalErrors + (a.lastError ? "<br><span style=\\"color:var(--red)\\">" + a.lastError + "</span>" : "") + "</div></div>";',
        '      }',
        '      list.innerHTML = html;',
        '    })',
        '    .catch(function(e) { toast("Load failed: " + e.message,"#f85149"); });',
        '}',
        '',
        'function sc(v,l) { return "<div class=\\"stat-card\\"><div class=\\"number\\">" + v + "</div><div class=\\"label\\">" + l + "</div></div>"; }',
        '',
        'function refreshAll() {',
        '  fetch("/admin/refresh-all",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(d){toast("Refreshed "+d.refreshed+"/"+d.total,"#3fb950");loadDashboard()}).catch(function(e){toast(e.message,"#f85149")});',
        '}',
        'function rescanConfigs() {',
        '  fetch("/admin/rescan",{method:"POST",headers:hdr()}).then(function(r){return r.json()}).then(function(d){toast("Found "+d.added+" new","#3fb950");loadDashboard()}).catch(function(e){toast(e.message,"#f85149")});',
        '}',
        '',
        'function startOAuth(method) {',
        '  var el = document.getElementById("authResult");',
        '  el.style.display = "block";',
        '  el.innerHTML = "<p style=\\"color:var(--dim)\\">Starting " + method + "...</p>";',
        '  fetch("/auth/kiro/oauth",{method:"POST",headers:hdr(),body:JSON.stringify({method:method})})',
        '    .then(function(r){return r.json()})',
        '    .then(function(d){',
        '      if(d.authUrl){el.innerHTML="<p>Open this link:</p><a href=\\""+d.authUrl+"\\" target=\\"_blank\\">"+d.authUrl+"</a><p style=\\"margin-top:1rem;color:var(--dim)\\">Account auto-adds after auth.</p>";window.open(d.authUrl,"_blank");}',
        '      else{el.innerHTML="<p style=\\"color:var(--red)\\">Error: "+(d.error||"Unknown")+"</p>";}',
        '    }).catch(function(e){el.innerHTML="<p style=\\"color:var(--red)\\">"+e.message+"</p>";});',
        '}',
        '',
        'function importCreds() {',
        '  var raw = document.getElementById("importJSON").value;',
        '  var data; try { data = JSON.parse(raw); } catch(e) { toast("Invalid JSON","#f85149"); return; }',
        '  fetch("/admin/credentials/import",{method:"POST",headers:hdr(),body:JSON.stringify(data)})',
        '    .then(function(r){return r.json()})',
        '    .then(function(d){if(d.success){toast("Imported!","#3fb950");document.getElementById("importJSON").value="";}else toast("Failed: "+d.error,"#f85149");})',
        '    .catch(function(e){toast(e.message,"#f85149");});',
        '}',
        '',
        'function batchImport() {',
        '  var lines = document.getElementById("batchTokens").value.split("\\n").filter(function(s){return s.trim();});',
        '  if(lines.length===0){toast("No tokens","#f85149");return;}',
        '  fetch("/admin/credentials/batch-import",{method:"POST",headers:hdr(),body:JSON.stringify({refreshTokens:lines})})',
        '    .then(function(r){return r.json()})',
        '    .then(function(d){var el=document.getElementById("batchResult");el.classList.remove("hidden");el.textContent=JSON.stringify(d,null,2);toast(d.success+" ok, "+d.failed+" failed",d.success>0?"#3fb950":"#f85149");})',
        '    .catch(function(e){toast(e.message,"#f85149");});',
        '}',
        '',
        'function exportJSON() {',
        '  fetch("/admin/credentials/export",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){var el=document.getElementById("exportBox");el.classList.remove("hidden");el.textContent=JSON.stringify(d.credentials,null,2);}).catch(function(e){toast(e.message,"#f85149");});',
        '}',
        'function exportBase64() {',
        '  fetch("/admin/credentials/export-base64",{headers:hdr()}).then(function(r){return r.json()}).then(function(d){var el=document.getElementById("exportBox");el.classList.remove("hidden");el.textContent=d.base64;copyText(d.base64);toast("Base64 copied!","#3fb950");}).catch(function(e){toast(e.message,"#f85149");});',
        '}',
        '',
        'function copyText(text) {',
        '  navigator.clipboard.writeText(text).then(function(){toast("Copied!","#3fb950")}).catch(function(){',
        '    var ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta);toast("Copied!","#3fb950");',
        '  });',
        '}',
        '',
        'function toast(msg,color) {',
        '  var t=document.getElementById("toast");t.textContent=msg;t.style.background=color||"#3fb950";t.style.display="block";setTimeout(function(){t.style.display="none";},3000);',
        '}',
        '',
        'renderModels();',
        'showPage("models");',
    ].join('\n');

    return '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        + '<meta charset="utf-8">\n'
        + '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        + '<title>Kiro2 API</title>\n'
        + '<style>\n' + css + '\n</style>\n'
        + '</head>\n<body>\n'
        + bodyHTML + '\n'
        + '<script>\n' + js + '\n</script>\n'
        + '</body>\n</html>';
}

export function buildModelsPage(freeModels, paidModels) {
    var cards = '';
    for (var i = 0; i < freeModels.length; i++) {
        cards += '<div class="mc" data-m="' + freeModels[i] + '"><span class="b free">FREE</span><h3>' + freeModels[i] + '</h3><small>Click to copy</small></div>';
    }
    var paidCards = '';
    for (var i = 0; i < paidModels.length; i++) {
        paidCards += '<div class="mc" data-m="' + paidModels[i] + '"><span class="b paid">PRO</span><h3>' + paidModels[i] + '</h3><small>Click to copy</small></div>';
    }

    return '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
        + '<title>Kiro2 API Models</title>'
        + '<style>'
        + '*{box-sizing:border-box;margin:0;padding:0}body{font-family:system-ui;background:#0d1117;color:#c9d1d9;padding:2rem}'
        + 'h1{text-align:center;margin-bottom:.5rem;color:#58a6ff}h2{margin:2rem 0 1rem;color:#8b949e;border-bottom:1px solid #21262d;padding-bottom:.5rem}'
        + '.sub{text-align:center;color:#8b949e;margin-bottom:2rem}'
        + '.g{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:1rem}'
        + '.mc{background:#161b22;border:1px solid #30363d;border-radius:12px;padding:1.5rem;position:relative;cursor:pointer;transition:all .2s}'
        + '.mc:hover{transform:translateY(-2px);border-color:#58a6ff}'
        + '.mc h3{margin:.4rem 0;font-size:1rem}.mc small{color:#8b949e}'
        + '.b{position:absolute;top:10px;right:10px;font-size:.65rem;font-weight:700;padding:3px 8px;border-radius:20px}'
        + '.b.free{background:#238636;color:#fff}.b.paid{background:#8957e5;color:#fff}'
        + '.t{position:fixed;bottom:20px;right:20px;background:#238636;color:#fff;padding:10px 20px;border-radius:8px;display:none;z-index:999}'
        + '</style></head><body>'
        + '<h1>Kiro2 API</h1><p class="sub">Available Models</p>'
        + '<h2>Free Tier</h2><div class="g">' + cards + '</div>'
        + '<h2>Pro Tier</h2><div class="g">' + paidCards + '</div>'
        + '<div class="t" id="t">Copied!</div>'
        + '<script>'
        + 'document.querySelectorAll(".mc").forEach(function(el){'
        + 'el.onclick=function(){var m=this.getAttribute("data-m");'
        + 'navigator.clipboard.writeText(m).then(function(){var t=document.getElementById("t");t.style.display="block";setTimeout(function(){t.style.display="none"},1500)});'
        + '};});'
        + '</script></body></html>';
}
